//! Types for validating transactions in each era.

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum ValidationError {
    TxAndProtParamsDiffer,
    UnknownProtParams,
    Byron(ByronError),
    ShelleyMA(ShelleyMAError),
    Alonzo(AlonzoError),
    Babbage(BabbageError),
}

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum ByronError {
    TxInsEmpty,
    TxOutsEmpty,
    InputNotInUTxO,
    OutputWithoutLovelace,
    UnknownTxSize,
    UnableToComputeFees,
    FeesBelowMin,
    MaxTxSizeExceeded,
    MissingWitness,
    WrongSignature,
    UnknownTxOutFormat,
    UnknownAddressFormat,
    UnknownWitnessFormat,
    EncodingErrorWitsCheck,
}

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum ShelleyMAError {
    TxInsEmpty,
    InputNotInUTxO,
    TTLExceeded,
    AlonzoCompNotShelley,
    UnknownTxSize,
    MaxTxSizeExceeded,
    MinLovelaceUnreached,
    PreservationOfValueProp,
    NegativeValue,
    FeesBelowMin,
    WrongEraOutput,
    AddressDecoding,
    WrongNetworkID,
    WrongMetadataHash,
    MissingVKWitness,
    MissingScriptWitness,
    WrongSignature,
    MintingLacksPolicy,
    UnknownAddressFormat,
    UnknownInputFormat,
    UnknownValueFormat,
    MissingAuxDataHash,
    UnneededAuxDataHash,
}

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum AlonzoError {
    UnknownTxSize,
    TxInsEmpty,
    InputNotInUTxO,
    CollateralNotInUTxO,
    BlockPrecedesValInt,
    BlockExceedsValInt,
    ValIntUpperBoundMissing,
    FeeBelowMin,
    CollateralMissing,
    TooManyCollaterals,
    CollateralNotVKeyLocked,
    AddressDecoding,
    CollateralMinLovelace,
    NonLovelaceCollateral,
    NegativeValue,
    PreservationOfValue,
    MinLovelaceUnreached,
    MaxValSizeExceeded,
    OutputWrongNetworkID,
    TxWrongNetworkID,
    TxExUnitsExceeded,
    MaxTxSizeExceeded,
    VKWitnessMissing,
    VKWrongSignature,
    ReqSignerMissing,
    ReqSignerWrongSig,
    ScriptWitnessMissing,
    MintingLacksPolicy,
    UnneededNativeScript,
    UnneededPlutusScript,
    RedeemerMissing,
    UnneededRedeemer,
    DatumMissing,
    UnneededDatum,
    RedeemerAndDatumMissing,
    WrongMetadataHash,
    AuxDataHashMissing,
    UnneededAuxDataHash,
    ScriptIntegrityHash,
    UnknownAddressFormat,
}

#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum BabbageError {
    UnknownTxSize,
    TxInsEmpty,
    InputNotInUTxO,
    CollateralNotInUTxO,
    ReferenceInputNotInUTxO,
    BlockPrecedesValInt,
    BlockExceedsValInt,
    FeeBelowMin,
    CollateralMissing,
    TooManyCollaterals,
    CollateralNotVKeyLocked,
    CollateralMinLovelace,
    NonLovelaceCollateral,
    NegativeValue,
    CollateralAnnotation,
    PreservationOfValue,
    MinLovelaceUnreached,
    MaxValSizeExceeded,
    OutputWrongNetworkID,
    TxWrongNetworkID,
    TxExUnitsExceeded,
    RedeemerMissing,
    UnneededRedeemer,
    DatumMissing,
    UnneededDatum,
    RedeemerAndDatumMissing,
    MaxTxSizeExceeded,
    MintingLacksPolicy,
    WrongMetadataHash,
    AuxDataHashMissing,
    UnneededAuxDataHash,
    ScriptWitnessMissing,
    UnneededNativeScript,
    UnneededPlutusV1Script,
    UnneededPlutusV2Script,
    ReqSignerMissing,
    ReqSignerWrongSig,
    VKWitnessMissing,
    VKWrongSignature,
    UnsupportedPlutusLanguage,
    ScriptIntegrityHash,
    UnknownAddressFormat,
}

pub type ValidationResult = Result<(), ValidationError>;
