[package]
name = "p2p2"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallas-network = { path = "../../pallas-network" }
pallas-network2 = { path = "../../pallas-network2" }
hex = "0.4.3"
log = "0.4.16"
thiserror = "1.0.31"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
