[package]
name = "leios-fetch-demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pallas = { path = "../../pallas", features = ["leios"]}
hex = "0.4.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
clap = { version = "4.5.50", features = ["derive"] }
